name: Build imagebuilder
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:


    - name: Delete Files
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Show system
      run: |
        lscpu
        free -h
        df -Th
        uname -a

    - name: Installation depends
      run: |
        sudo -E apt update -y
        sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
        vim wget xmlto xxd zlib1g-dev python3-setuptools
    
    - name: Clone source code
      run: |
        wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-imagebuilder-23.05.0-x86-64.Linux-x86_64.tar.xz
        tar -J -x -f openwrt-imagebuilder-23.05.0-x86-64.Linux-x86_64.tar.xz
        
    - name: Packages
      run: |
        cd openwrt-imagebuilder-23.05.0-x86-64.Linux-x86_64
        wget -P ./packages https://github.com/tty228/luci-app-wechatpush/releases/download/v3.3.3/luci-app-wechatpush_3.3.3_all.ipk
        wget -P ./packages https://github.com/tty228/luci-app-wechatpush/releases/download/v3.3.3/luci-i18n-wechatpush-zh-cn_git-23.288.19319-c68c19c_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-passwall_4.71-2_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-i18n-passwall-zh-cn_git-23.291.10149-ad47f73_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/chinadns-ng_2023.06.01-1_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/dns2socks_2.1-2_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/dns2tcp_1.1.0-3_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/ipt2socks_1.1.3-3_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/shadowsocksr-libev-ssr-local_2.5.6-9_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/shadowsocksr-libev-ssr-redir_2.5.6-9_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/simple-obfs-client_0.0.5-1_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/tcping_0.3-2_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/trojan-plus_10.0.3-2_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/v2ray-plugin_5.8.0-1_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-alist_git-23.274.11309-859245b_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/alist_3.28.0-1_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-autoreboot_1.0_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-lib-fs_1.0-2_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-filetransfer_git-23.274.11309-859245b_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-ramfree_1.0_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-ddns-go_git-23.274.11309-859245b_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/ddns-go_5.6.3-1_x86_64.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-openclash_0.45.141-beta_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-unblockneteasemusic_3.2_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/luci/luci-app-zerotier_git-23.274.11309-859245b_all.ipk
        wget -P ./packages https://downloads.immortalwrt.org/releases/23.05.0-rc4/packages/x86_64/packages/zerotier_1.12.2-1_x86_64.ipk
        
    
    - name: Build 
      run: |
        cd openwrt-imagebuilder-23.05.0-x86-64.Linux-x86_64
        sed -i 's/CONFIG_TARGET_ROOTFS_EXT4FS=y/#CONFIG_TARGET_ROOTFS_EXT4FS is not set/' .config
        sed -i 's/CONFIG_ISO_IMAGES=y/#CONFIG_ISO_IMAGES is not set/' .config
        sed -i 's/CONFIG_QCOW2_IMAGES=y/#CONFIG_QCOW2_IMAGES is not set/' .config
        sed -i 's/CONFIG_VDI_IMAGES=y/#CONFIG_VDI_IMAGES is not set/' .config
        sed -i 's/CONFIG_VMDK_IMAGES=y/#CONFIG_VDI_IMAGES is not set/' .config
        sed -i 's/CONFIG_VHDX_IMAGES=y/#CONFIG_VHDX_IMAGES is not set/' .config
        sed -i 's/CONFIG_TARGET_ROOTFS_PARTSIZE=300/CONFIG_TARGET_ROOTFS_PARTSIZE=500/' .config
       
        
        make image PACKAGES="kmod-alx luci-i18n-base-zh-cn luci-i18n-opkg-zh-cn luci-i18n-firewall-zh-cn kmod-tun luci-compat luci-lib-ip htop coremark ca-bundle kmod-sched-core kmod-sched-bpf kmod-nf-socket kmod-nf-tproxy kmod-nft-socket kmod-nft-tproxy hysteria luci-app-alist luci-app-ddns-go luci-app-filetransfer luci-app-firewall luci-app-ramfree luci-app-openclash luci-app-passwall luci-app-unblockneteasemusic luci-app-wechatpush luci-app-zerotier luci-i18n-alist-zh-cn luci-i18n-daed-zh-cn luci-i18n-ddns-go-zh-cn luci-i18n-filetransfer-zh-cn luci-i18n-ramfree-zh-cn luci-i18n-passwall-zh-cn luci-i18n-wechatpush-zh-cn luci-i18n-zerotier-zh-cn"

    - name: Upload firmware
      uses: actions/upload-artifact@master
      with: 
        name: openwrt-imagebuilder-23.05.0-x86-64.Linux-x86_64-firmware
        path: openwrt-imagebuilder-23.05.0-x86-64.Linux-x86_64/bin/targets/
